apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: gprc-port
      protocol: GRPC
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: internal-service
  namespace: default
spec:
  hosts:
  - micro-internal
  http:
  - match:
    - uri:
        prefix: /Internal.InternalService/
    route:
    - destination:
        port:
          number: 8080
        host: micro-internal.microservices.svc.cluster.local
    retries:
      attempts: 25
      perTryTimeout: 1s
